site_name: ostrade
theme:
  name: material
nav:
  - Motivation and Hypothesis: 'index.md'
  - Foundational Services: 'foundations.md'
  - Technology: 'technology.md'
  - Project Structure: 'projects.md'
  - Foundations:
      - 'Protobuf Domain': 'foundations/protodomain.md'
      - 'Instrument': 'foundations/instrument.md'
      - 'Counterparty': 'foundations/counterparty.md'
      - 'Trade': 'foundations/trade.md'
      - 'Market Data': 'foundations/marketdata.md'